"""Create userts tables

Revision ID: 3b58e4147fc2
Revises: 4e32be5299e0
Create Date: 2026-03-27 16:57:43.915566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b58e4147fc2'
down_revision: Union[str, Sequence[str], None] = '4e32be5299e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("DELETE FROM categories") 
    op.execute("TRUNCATE TABLE categories CASCADE;")
    op.execute("DELETE FROM products") 
    op.execute("DELETE FROM users") 
    op.add_column('categories', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'admin_id')
    # ### end Alembic commands ###
