"""Add field created_at updated_at in products tables

Revision ID: a8a84a9689c7
Revises: 1154aeb4ac87
Create Date: 2026-04-06 15:00:14.522815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a84a9689c7'
down_revision: Union[str, Sequence[str], None] = '1154aeb4ac87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###
