"""Create Search Vector

Revision ID: d552b980f119
Revises: e6b10561bc65
Create Date: 2026-04-07 14:45:43.099156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd552b980f119'
down_revision: Union[str, Sequence[str], None] = 'e6b10561bc65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('english', coalesce(name, '')), 'A')\n            || \n            setweight(to_tsvector('english', coalesce(description, '')), 'B')\n            ", persisted=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tsv')
    # ### end Alembic commands ###
